### ISSUE TITLE
Issue in calculating width of the label

### ISSUE THREAD

**Issue by vinsar12** [fntneves/jquery-labelauty#10]
The unchecked_width and checked_width seems to be returning 0 when the plugin is used in a tab which is inactive.

PFA the screenshot.

![capture](https://cloud.githubusercontent.com/assets/10353378/5583947/e93f0058-904e-11e4-9368-df735c22be08.PNG)

This might not be an issue too. Just wanted to report this :)

Thanks guys.

**Comment by fntneves** [comment]
Thank you. This is not a bug of width calculation, jQuery returns 0 because display:none when tab is disabled.

I have two alternatives:
Add an "onShow" event for each hidden input.
Use a tricky code (based on jquery.actual plugin).

I may prefer latter.

Thank you for reporting. I'll fix that.

Happy new year. :+1:
